# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77f6d0dab85100fe8f5d09861086ddb8a0ad62b8fcb25d2fb7e4dd7a2e41887a99b3ac705b74ef97b5774e49fb2477a858bf3e439688cf30d54d4dad1e73c2fb

test:
  secret_key_base: db3dfeec0da8ef5caac50dfb1a719522820533a0f851bddaf32d950abe611f3919880d279b8053f4bea8dd7e832d4a1c8a5d5c5675e9db57eed4403d3c90d24b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
